version: '2'
services:
    gallery-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/gallery/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=gallery
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
